# Generated by Django 5.2.7 on 2026-01-01 11:48

import sample_questions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان سوال')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('pdf_file', models.FileField(upload_to=sample_questions.models.question_pdf_path, verbose_name='فایل PDF سوالات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'سوال نمونه',
                'verbose_name_plural': 'سوالات نمونه',
                'ordering': ['-created_at'],
            },
        ),
    ]
