# Generated by Django 6.0 on 2026-01-07 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samplequestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'نمونه سوال ها', 'verbose_name_plural': 'نمونه سوال ها'},
        ),
    ]
