# Generated by Django 6.0 on 2026-05-18 10:57

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    SampleQuestion = apps.get_model('sample_questions', 'SampleQuestion')
    used = set()
    for obj in SampleQuestion.objects.all().order_by('id'):
        base = slugify(obj.title, allow_unicode=True) or f'sample-{obj.pk}'
        slug = base
        n = 1
        while slug in used:
            slug = f'{base}-{n}'
            n += 1
        used.add(slug)
        obj.slug = slug
        obj.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('sample_questions', '0002_alter_samplequestion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplequestion',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='توضیح SEO'),
        ),
        migrations.AddField(
            model_name='samplequestion',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=False),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='samplequestion',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True),
        ),
    ]
