# Generated by Django 6.0 on 2026-05-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_questions', '0003_samplequestion_meta_description_samplequestion_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplequestion',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='samplequestion',
            name='slug',
        ),
    ]
