# Generated by Django 6.0 on 2026-06-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_questions', '0004_remove_samplequestion_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplequestion',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True, verbose_name='شناسه URL'),
        ),
    ]
