# Generated by Django 6.0 on 2026-06-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuidePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='شناسه URL')),
                ('meta_description', models.CharField(max_length=320, verbose_name='توضیحات متا')),
                ('meta_keywords', models.CharField(blank=True, max_length=300, verbose_name='کلمات کلیدی')),
                ('excerpt', models.TextField(max_length=500, verbose_name='خلاصه')),
                ('content', models.TextField(verbose_name='محتوا (HTML)')),
                ('icon', models.CharField(default='fas fa-book', max_length=60, verbose_name='آیکون FontAwesome')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صفحه آموزشی',
                'verbose_name_plural': 'صفحات آموزشی',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
