# Generated by Django 5.2.7 on 2026-01-05 08:58

import django.db.models.deletion
import quizbuilder_module.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('desc', models.TextField(max_length=500, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('open', 'باز'), ('close', 'بسته')], default='open', max_length=50, verbose_name='وضعیت')),
                ('time', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان آزمون (دقیقه)')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان آزمون')),
            ],
            options={
                'verbose_name': 'آزمون',
                'verbose_name_plural': 'آزمون ها',
            },
            bases=(quizbuilder_module.mixins.QuizStartedSmsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QuizQuestionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, verbose_name='متن جواب')),
                ('is_answer', models.BooleanField(default=False, verbose_name='جواب صحیح است؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='متن سوال')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='بارم')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizbuilder_module.quiz', verbose_name='آزمون')),
                ('choices', models.ManyToManyField(to='quizbuilder_module.quizquestionchoice', verbose_name='گزینه های سوال')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در حال انجام'), ('done', 'انجام شده'), ('pass', 'پاس شده'), ('fail', 'رد شده')], default='pending', max_length=255, verbose_name='وضعیت')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع آزمون')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='نمره(بارم)')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quizzes', to='quizbuilder_module.quiz', verbose_name='آزمون')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuizQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizbuilder_module.quizquestionchoice', verbose_name='پاسخ کاربر')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizbuilder_module.quizquestion', verbose_name='سوال')),
                ('user_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quiz_questions', to='quizbuilder_module.userquiz', verbose_name='پاسخنامه کاربر')),
            ],
        ),
    ]
