# Generated by Django 6.0 on 2026-05-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizbuilder_module', '0005_alter_quiz_id_alter_quizquestion_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'verbose_name': 'متن سوال', 'verbose_name_plural': 'متن سوال ها'},
        ),
        migrations.AlterModelOptions(
            name='quizquestionchoice',
            options={'ordering': ['created_at'], 'verbose_name': 'گزینه ها', 'verbose_name_plural': 'گزینه ها'},
        ),
        migrations.AlterModelOptions(
            name='userquiz',
            options={'verbose_name': 'پاسخ نامه کاربر', 'verbose_name_plural': 'پاسخ نامه های کاربران'},
        ),
        migrations.AlterModelOptions(
            name='userquizquestionanswer',
            options={'verbose_name': 'پاسخ های کاربر', 'verbose_name_plural': 'پاسخ های کاربران'},
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='تصویر سوال'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quizquestionchoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userquizquestionanswer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
