# Generated by Django 6.0 on 2026-05-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizbuilder_module', '0006_alter_quizquestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestionchoice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_options/', verbose_name='تصویر گزینه'),
        ),
    ]
