# Generated by Django 6.0 on 2026-05-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizbuilder_module', '0008_userquiz_share_and_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'پیشنهادی مبتدی'), ('intermediate', 'متوسط'), ('exam_like', 'شبیه آزمون واقعی')], default='intermediate', max_length=20, verbose_name='سطح'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_beginner_recommended',
            field=models.BooleanField(default=False, verbose_name='پیشنهاد برای مبتدی'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='topic',
            field=models.CharField(blank=True, choices=[('signs', 'تابلو و علائم'), ('rules', 'قوانین راهنمایی'), ('right_of_way', 'حق تقدم'), ('speed', 'سرعت و فاصله'), ('safety', 'ایمنی و کمک\u200cهای اولیه'), ('parking', 'توقف و پارک'), ('other', 'سایر')], default='other', max_length=30, verbose_name='موضوع'),
        ),
    ]
