# Generated by Django 6.0 on 2026-05-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizbuilder_module', '0009_quiz_difficulty_quiz_is_beginner_recommended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_beginner_recommended',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='topic',
        ),
    ]
