# Generated by Django 6.0 on 2026-06-06 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizbuilder_module', '0011_dynamic_exam_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='exam_type',
            field=models.CharField(choices=[('standard', 'آزمون عادی'), ('wrong_practice', 'تمرین سوالات اشتباه')], default='standard', max_length=20, verbose_name='نوع آزمون'),
        ),
        migrations.CreateModel(
            name='WrongQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_count', models.PositiveIntegerField(default=1, verbose_name='تعداد اشتباه')),
                ('consecutive_correct', models.PositiveSmallIntegerField(default=0, verbose_name='پاسخ صحیح پیاپی در تمرین')),
                ('first_wrong_at', models.DateTimeField(auto_now_add=True, verbose_name='اولین اشتباه')),
                ('last_wrong_at', models.DateTimeField(auto_now=True, verbose_name='آخرین اشتباه')),
                ('is_mastered', models.BooleanField(default=False, verbose_name='یاد گرفته شده')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_records', to='quizbuilder_module.question', verbose_name='سوال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_questions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سوال اشتباه',
                'verbose_name_plural': 'سوالات اشتباه کاربران',
                'ordering': ['-last_wrong_at'],
                'indexes': [models.Index(fields=['user', 'is_mastered'], name='quizbuilder_user_id_dbad2a_idx'), models.Index(fields=['user', '-last_wrong_at'], name='quizbuilder_user_id_20a13a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'question'), name='unique_wrong_question_per_user')],
            },
        ),
    ]
