# Generated by Django 5.2.7 on 2026-01-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_alter_user_email_alter_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='exam_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد آزمون\u200cهای رایگان امروز'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_paid_for_exam',
            field=models.BooleanField(default=False, verbose_name='آیا برای آزمون پرداخت کرده است؟'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_attempt_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین آزمون'),
        ),
    ]
