# Generated by Django 6.0 on 2026-05-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.PositiveIntegerField(default=0, verbose_name='اعتبار آزمون'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='اشتراک ماهانه/سالانه فعال.', verbose_name='کاربر پرمیوم'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(choices=[('free', 'رایگان'), ('credit', 'اعتباری'), ('premium', 'پرمیوم'), ('expired', 'منقضی')], default='free', max_length=20, verbose_name='وضعیت اشتراک'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_paid_for_exam',
            field=models.BooleanField(default=False, help_text='فیلد legacy — ترجیحاً از اشتراک/اعتبار استفاده شود.', verbose_name='پرداخت قدیمی آزمون'),
        ),
    ]
