# Generated by Django 6.0 on 2026-05-16 10:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه یکتا')),
                ('name', models.CharField(max_length=120, verbose_name='نام پلن')),
                ('plan_type', models.CharField(choices=[('free', 'رایگان'), ('credit', 'بسته اعتباری'), ('monthly', 'ماهانه'), ('yearly', 'سالانه')], max_length=20, verbose_name='نوع پلن')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(default=0, help_text='برای پلن رایگان صفر باشد.', verbose_name='قیمت (تومان)')),
                ('credits_amount', models.PositiveIntegerField(default=0, help_text='فقط برای بسته\u200cهای اعتباری.', verbose_name='تعداد اعتبار')),
                ('duration_days', models.PositiveIntegerField(default=0, help_text='برای پلن ماهانه/سالانه.', verbose_name='مدت اشتراک (روز)')),
                ('daily_free_attempts', models.PositiveSmallIntegerField(default=2, help_text='فقط برای پلن رایگان.', verbose_name='آزمون رایگان روزانه')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='لیست امکانات')),
                ('is_popular', models.BooleanField(default=False, verbose_name='پلن محبوب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پلن اشتراک',
                'verbose_name_plural': 'پلن\u200cهای اشتراک',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('authority', models.CharField(blank=True, help_text='Authority زرین\u200cپال یا مشابه.', max_length=64, verbose_name='کد مرجع درگاه')),
                ('ref_id', models.CharField(blank=True, max_length=64, verbose_name='شماره پیگیری')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='subscriptions_module.subscriptionplan', verbose_name='پلن')),
            ],
            options={
                'verbose_name': 'سفارش پرداخت',
                'verbose_name_plural': 'سفارش\u200cهای پرداخت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'خرید اعتبار'), ('consume', 'مصرف در آزمون'), ('refund', 'بازگشت'), ('bonus', 'هدیه')], max_length=20, verbose_name='نوع تراکنش')),
                ('amount', models.IntegerField(help_text='مثبت برای افزایش، منفی برای کاهش اعتبار.', verbose_name='مقدار')),
                ('balance_after', models.PositiveIntegerField(verbose_name='موجودی پس از تراکنش')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='subscriptions_module.paymentorder', verbose_name='سفارش')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='subscriptions_module.subscriptionplan', verbose_name='پلن مرتبط')),
            ],
            options={
                'verbose_name': 'تراکنش اعتبار',
                'verbose_name_plural': 'تراکنش\u200cهای اعتبار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('expired', 'منقضی'), ('cancelled', 'لغو شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='شروع')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_subscriptions', to='subscriptions_module.subscriptionplan', verbose_name='پلن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اشتراک کاربر',
                'verbose_name_plural': 'اشتراک\u200cهای کاربران',
                'ordering': ['-started_at'],
            },
        ),
    ]
